import { Title, Link, Meta } from "react-head";

const MetaTags = () => (
  <>
    <Title>Div Replacement App</Title>
    <Meta
      name="description"
      content="Generated by create-t3-app, refactored to use div replacement"
    />
    <Link rel="icon" href="/favicon.ico" />
  </>
);

export default MetaTags;
